#! /usr/bin/env perl

use strict;
use warnings;

use IO::Handle;

if( @ARGV == 0 ) {
	die "Usage: newline <col-width> <optional path>\n";
}

my $count = shift @ARGV;
my $path = shift @ARGV;

my $fh;

$| = 1;

if( $path ) {
	open $fh, '<', $path or die "cannot open file $path\n";
} else {
	$fh = *STDIN;
}

$fh->autoflush( 1 );

my $buffer;
while( ( my $len = sysread( $fh, $buffer, $count ) ) != 0 ) {
	syswrite( STDOUT, $buffer, $len );
	syswrite( STDOUT, "\n", 1 );
}