#! /usr/bin/env perl

use strict;
use warnings;

use IO::Handle;

if( @ARGV == 0 ) {
	die "Usage: seek <bytes> <optional path>\n";
}

my $count = shift @ARGV;
my $path = shift @ARGV;

my $fh;

$| = 1;

if( $path ) {
	open $fh, '<', $path or die "cannot open file $path\n";
} else {
	$fh = *STDIN;
}

$fh->autoflush( 1 );

my $buffer1;
sysread( $fh, $buffer1, $count );

my $buffer2;
while( ( my $len = sysread( $fh, $buffer2, 1024 ) ) != 0 ) {
	syswrite( STDOUT, $buffer2, $len );
}