#! /usr/bin/env perl

use strict;
use warnings;

use IO::Handle;

if( @ARGV == 0 ) {
	die "Usage: take <bytes> <optional path>\n";
}

my $count = shift @ARGV;
my $path = shift @ARGV;

my $fh;

$| = 1;

if( $path ) {
	open $fh, '<', $path or die "cannot open file $path\n";
} else {
	$fh = *STDIN;
}

my $buffer;
my $len = sysread( $fh, $buffer, $count );
syswrite( STDOUT, $buffer, $len );
close( STDOUT );